version: '3.8'
services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ../data:/app/data
  ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: ["python", "-m", "app.ui.flask_app"]
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ../data:/app/data
